---
- hosts: localhost
  connection: local
  become: True
  gather_facts: False

  vars: 
    - user: rafael

  tasks:
    - name: Update and upgrade apt packages
      become: True
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Get Kernel version
      shell: uname -r
      register: kernel_shell_output
    
    - debug: msg="linux-headers-{{ kernel_shell_output.stdout}}"

    - name: install linux-headers
      apt: name="linux-headers-{{ kernel_shell_output.stdout}}" state=present

    - name: Install Tools 
      apt: 
        state: latest
        name: 
          - build-essential
          - curl 
          - wget
          - vim
          - xclip
          - software-properties-common
          - git
          - htop
          - vlc
          - tmux
          - snapd
          - unrar
          - keepassx
          - gimp

    - name: install parcellite
      apt:
        state: latest
        name: parcellite
    
    - name: check parcellite conf folder exists
      stat:
        path: "/home/{{ user }}/.config/parcellite/"
      register: parcellite_conf_folder
  
    - name: create parcellite conf folder if not exists
      file:
        path: "/home/{{ user }}/.config/parcellite/"
        state: directory
      when: not parcellite_conf_folder.stat.exists

    - name: configure parcellite
      get_url:
        url: https://raw.githubusercontent.com/carreirorco/dotfiles/master/parcellite/parcelliterc
        dest: "/home/{{ user }}/.config/parcellite/parcelliterc"
        mode: '0644'
        force: yes

    - name: install terminator
      apt: 
        state: latest
        name: terminator

    - name: Install a .deb package for google chrome.
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: install flameshot
      apt: 
        state: latest
        name: flameshot

    - name: install virtualbox
      apt:
        state: latest
        name: [virtualbox, linux-headers-virtual, virtualbox-dkms]

    - name: install vagrant
      apt:
        state: latest
        name: vagrant

    - name: install visual studio code
      snap: 
        name: code
        state: present
        classic: yes

    - name: install slack
      snap: 
        name: slack
        state: present
        classic: yes
      
    - name: install zoom-client
      snap: 
        name: zoom-client
        state: present

    - name: install skype
      snap: 
        name: skype
        state: present
        classic: yes

    - name: install discord
      snap: 
        name: discord
        state: present
        classic: yes

    - name: install postman
      snap: 
        name: postman
        state: present

    - name: install spotify
      snap: 
        name: spotify
        state: present

    - name: install retroarch
      snap:
        name: retroarch
        state: present

    - name: install woe-usb
      snap:
        name: woe-usb
        state: present
        channel: latest/edge